{% set name = "napari-threedee" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 151991bb1bbac6e24f6561c7b87c4a2ba757d5572790b9f408d7a18ab83da69c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - einops
    # - igl # feedstock currently abandoned
    - magicgui
    - napari
    - numpy
    - pandas
    - pydantic
    - psygnal
    - qtpy
    - scipy
    - superqt
    - vispy
    - zarr
    - morphosamplers

test:
  imports:
    - napari_threedee
  # commands:
  # pip check fails to recognize igl as libigl
  #  - pip check
  requires:
    - pyqt
  #  - pip

about:
  home: https://github.com/alisterburt/napari-threedee
  summary: A suite of useful tools based on 3D interactivity in napari
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - kevinyamauchi
    - alisterburt
    - psobolewskiPhD
